version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 806263725031.dkr.ecr.ap-south-1.amazonaws.com 
      - REPOSITORY_URI=806263725031.dkr.ecr.ap-south-1.amazonaws.com/nodeapp
     
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t nodeapp .
      - docker tag nodeapp:latest 806263725031.dkr.ecr.ap-south-1.amazonaws.com/nodeapp:latest
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker images...
      - docker push 806263725031.dkr.ecr.ap-south-1.amazonaws.com/nodeapp:latest
    

